In [1]:
import os
from dotenv import load_dotenv
import requests
import pandas as pd
import json
from pandas import json_normalize
import re

load_dotenv

token = os.getenv("API_TOKEN")

headers = {
    'Authorization': f'Bearer {token}',
    'Content-Type': 'application.json'
}
response = requests.get('https://api.clashofclans.com/v1/clans/%232GLLPQYLL/currentwar', headers=headers)
response = response.json()

In [2]:
# with open('war1.json', "r") as json_data:
#     response = json.load(json_data)

In [3]:
data = json_normalize(response, record_path=['opponent', 'members'])
data

,tag,name,townhallLevel,mapPosition,opponentAttacks,bestOpponentAttack.attackerTag,bestOpponentAttack.defenderTag,bestOpponentAttack.stars,bestOpponentAttack.destructionPercentage,bestOpponentAttack.order,bestOpponentAttack.duration,attacks
0,#QR9GLUCLP,Mahdi✌️❤️,12,7,2,#8CRG2JR9,#QR9GLUCLP,1.0,91.0,18.0,161.0,NaN
1,#URUQ92R,Afif ✌️,11,8,1,#GYQ09LYRR,#URUQ92R,2.0,94.0,11.0,129.0,"[{'attackerTag': '#URUQ92R', 'defenderTag': '#..."
2,#PCUGCRG,khair,13,3,1,#9PRCGP9Y,#PCUGCRG,3.0,100.0,19.0,92.0,"[{'attackerTag': '#PCUGCRG', 'defenderTag': '#..."
3,#2QQ9RQJ0P,♥️آلَشـ❣ـہآيبـ❣,16,1,1,#9GGVU8C8,#2QQ9RQJ0P,2.0,97.0,16.0,176.0,"[{'attackerTag': '#2QQ9RQJ0P', 'defenderTag': ..."
4,#G2ULQCCCC,الداينصوور,12,6,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,#PG8UYYYG2,AFIF,12,5,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'attackerTag': '#PG8UYYYG2', 'defenderTag': ..."
6,#G28LQQGL8,bigdevil,10,10,1,#LPG2LYYGJ,#G28LQQGL8,3.0,100.0,10.0,93.0,NaN
7,#99PY8V9C2,حسن ثابت,11,9,1,#GPRURPLRG,#99PY8V9C2,3.0,100.0,9.0,142.0,NaN
8,#YYRP8U8VY,FeHmi,16,2,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'attackerTag': '#YYRP8U8VY', 'defenderTag': ..."
9,#G8RLLL2YR,محمود,13,4,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'attackerTag': '#G8RLLL2YR', 'defenderTag': ..."

In [4]:
members_df = json_normalize(response, record_path=['opponent', 'members'], meta=[])
total_members_df = members_df.copy()

In [5]:
attacks_df = json_normalize(
    members_df.to_dict(orient='records'),  # Convert DataFrame to dicts
    record_path='attacks',
    meta=['name'],
    meta_prefix='member_'
)
attacks_df

,attackerTag,defenderTag,stars,destructionPercentage,order,duration,member_name
0,#URUQ92R,#LPG2LYYGJ,3,100,3,95,Afif ✌️
1,#URUQ92R,#GPRURPLRG,3,100,4,107,Afif ✌️
2,#PCUGCRG,#UGRL8LV8,3,100,5,121,khair
3,#PCUGCRG,#8Q8UQL8Y,3,100,6,69,khair
4,#2QQ9RQJ0P,#9GGVU8C8,1,78,12,128,♥️آلَشـ❣ـہآيبـ❣
5,#2QQ9RQJ0P,#9PRCGP9Y,2,52,15,49,♥️آلَشـ❣ـہآيبـ❣
6,#PG8UYYYG2,#8CRG2JR9,3,100,1,96,AFIF
7,#PG8UYYYG2,#GYQ09LYRR,3,100,2,92,AFIF
8,#YYRP8U8VY,#9GGVU8C8,2,75,7,63,FeHmi
9,#YYRP8U8VY,#9PRCGP9Y,3,100,8,87,FeHmi
10,#G8RLLL2YR,#G222UU009,3,100,13,84,محمود
11,#G8RLLL2YR,#GGV0JPQ2C,3,100,14,60,محمود

In [6]:
attacks_df['attack_num'] = attacks_df.groupby('member_name').cumcount() + 1
attacks_df

,attackerTag,defenderTag,stars,destructionPercentage,order,duration,member_name,attack_num
0,#URUQ92R,#LPG2LYYGJ,3,100,3,95,Afif ✌️,1
1,#URUQ92R,#GPRURPLRG,3,100,4,107,Afif ✌️,2
2,#PCUGCRG,#UGRL8LV8,3,100,5,121,khair,1
3,#PCUGCRG,#8Q8UQL8Y,3,100,6,69,khair,2
4,#2QQ9RQJ0P,#9GGVU8C8,1,78,12,128,♥️آلَشـ❣ـہآيبـ❣,1
5,#2QQ9RQJ0P,#9PRCGP9Y,2,52,15,49,♥️آلَشـ❣ـہآيبـ❣,2
6,#PG8UYYYG2,#8CRG2JR9,3,100,1,96,AFIF,1
7,#PG8UYYYG2,#GYQ09LYRR,3,100,2,92,AFIF,2
8,#YYRP8U8VY,#9GGVU8C8,2,75,7,63,FeHmi,1
9,#YYRP8U8VY,#9PRCGP9Y,3,100,8,87,FeHmi,2
10,#G8RLLL2YR,#G222UU009,3,100,13,84,محمود,1
11,#G8RLLL2YR,#GGV0JPQ2C,3,100,14,60,محمود,2

In [7]:
attacks_df['total_attacks'] = attacks_df.groupby('member_name')['attack_num'].transform('max')
attacks_df

,attackerTag,defenderTag,stars,destructionPercentage,order,duration,member_name,attack_num,total_attacks
0,#URUQ92R,#LPG2LYYGJ,3,100,3,95,Afif ✌️,1,2
1,#URUQ92R,#GPRURPLRG,3,100,4,107,Afif ✌️,2,2
2,#PCUGCRG,#UGRL8LV8,3,100,5,121,khair,1,2
3,#PCUGCRG,#8Q8UQL8Y,3,100,6,69,khair,2,2
4,#2QQ9RQJ0P,#9GGVU8C8,1,78,12,128,♥️آلَشـ❣ـہآيبـ❣,1,2
5,#2QQ9RQJ0P,#9PRCGP9Y,2,52,15,49,♥️آلَشـ❣ـہآيبـ❣,2,2
6,#PG8UYYYG2,#8CRG2JR9,3,100,1,96,AFIF,1,2
7,#PG8UYYYG2,#GYQ09LYRR,3,100,2,92,AFIF,2,2
8,#YYRP8U8VY,#9GGVU8C8,2,75,7,63,FeHmi,1,2
9,#YYRP8U8VY,#9PRCGP9Y,3,100,8,87,FeHmi,2,2
10,#G8RLLL2YR,#G222UU009,3,100,13,84,محمود,1,2
11,#G8RLLL2YR,#GGV0JPQ2C,3,100,14,60,محمود,2,2

In [8]:
total_attacks_df = attacks_df[['member_name', 'total_attacks']].drop_duplicates().set_index('member_name')
total_attacks_df

                 total_attacks
member_name
Afif ✌️                      2
khair                        2
♥️آلَشـ❣ـہآيبـ❣              2
AFIF                         2
FeHmi                        2
محمود                        2

In [9]:
pivot_df = attacks_df.pivot_table(
    index=['member_name'], 
    columns='attack_num', 
    values=['attackerTag', 'defenderTag', 'stars', 'destructionPercentage', 'order', 'duration'], 
    aggfunc='first'
)
pivot_df

                attackerTag             defenderTag              \
attack_num                1           2           1           2
member_name
AFIF             #PG8UYYYG2  #PG8UYYYG2   #8CRG2JR9  #GYQ09LYRR
Afif ✌️            #URUQ92R    #URUQ92R  #LPG2LYYGJ  #GPRURPLRG
FeHmi            #YYRP8U8VY  #YYRP8U8VY   #9GGVU8C8   #9PRCGP9Y
khair              #PCUGCRG    #PCUGCRG   #UGRL8LV8   #8Q8UQL8Y
محمود            #G8RLLL2YR  #G8RLLL2YR  #G222UU009  #GGV0JPQ2C
♥️آلَشـ❣ـہآيبـ❣  #2QQ9RQJ0P  #2QQ9RQJ0P   #9GGVU8C8   #9PRCGP9Y

                destructionPercentage      duration      order     stars
attack_num                          1    2        1    2     1   2     1  2
member_name
AFIF                              100  100       96   92     1   2     3  3
Afif ✌️                           100  100       95  107     3   4     3  3
FeHmi                              75  100       63   87     7   8     2  3
khair                             100  100      121   69     5   6     3  3
محمود                             100  100       84   60    13  14     3  3
♥️آلَشـ❣ـہآيبـ❣                    78   52      128   49    12  15     1  2

In [10]:
pivot_df.columns = [f"{col[0]}_{col[1]}" for col in pivot_df.columns]

In [11]:
def extract_text_and_number(column_name):
    match = re.match(r'(.+?)_(\d+)', column_name)
    return (int(match.group(2)), match.group(1)) if match else (float('inf'), column_name)

In [12]:
sorted_columns = sorted(pivot_df.columns, key=lambda x: extract_text_and_number(x))
sorted_columns

['attackerTag_1',
 'defenderTag_1',
 'destructionPercentage_1',
 'duration_1',
 'order_1',
 'stars_1',
 'attackerTag_2',
 'defenderTag_2',
 'destructionPercentage_2',
 'duration_2',
 'order_2',
 'stars_2']

In [13]:
pivot_df = pivot_df[sorted_columns]

In [14]:
final_df = pivot_df.join(total_attacks_df)
final_df

,attackerTag_1,defenderTag_1,destructionPercentage_1,duration_1,order_1,stars_1,attackerTag_2,defenderTag_2,destructionPercentage_2,duration_2,order_2,stars_2,total_attacks
member_name,,,,,,,,,,,,,
AFIF,#PG8UYYYG2,#8CRG2JR9,100,96,1,3,#PG8UYYYG2,#GYQ09LYRR,100,92,2,3,2
Afif ✌️,#URUQ92R,#LPG2LYYGJ,100,95,3,3,#URUQ92R,#GPRURPLRG,100,107,4,3,2
FeHmi,#YYRP8U8VY,#9GGVU8C8,75,63,7,2,#YYRP8U8VY,#9PRCGP9Y,100,87,8,3,2
khair,#PCUGCRG,#UGRL8LV8,100,121,5,3,#PCUGCRG,#8Q8UQL8Y,100,69,6,3,2
محمود,#G8RLLL2YR,#G222UU009,100,84,13,3,#G8RLLL2YR,#GGV0JPQ2C,100,60,14,3,2
♥️آلَشـ❣ـہآيبـ❣,#2QQ9RQJ0P,#9GGVU8C8,78,128,12,1,#2QQ9RQJ0P,#9PRCGP9Y,52,49,15,2,2

In [15]:
new_name_df = final_df
new_name_df['Avg %'] = new_name_df[['destructionPercentage_1', 'destructionPercentage_2']].mean(axis=1)
new_name_df['Total Stars'] = new_name_df[["stars_1", "stars_2"]].sum(axis=1)

In [16]:
new_order = ['total_attacks', 'Avg %', 'destructionPercentage_1', 'destructionPercentage_2', 
             'stars_1', 'stars_2', 'Total Stars']
new_name_df = new_name_df[new_order]
final_name_df = new_name_df.rename(columns={'destructionPercentage_1' : 'Attack 1 %', 'destructionPercentage_2' : 'Attack 2 %', 
                                            'stars_1' : 'Attack 1 Stars', 'stars_2' : 'Attack 2 Stars', 'total_attacks' : 'Total Attacks'})
final_name_df

,Total Attacks,Avg %,Attack 1 %,Attack 2 %,Attack 1 Stars,Attack 2 Stars,Total Stars
member_name,,,,,,,
AFIF,2,100.0,100,100,3,3,6
Afif ✌️,2,100.0,100,100,3,3,6
FeHmi,2,87.5,75,100,2,3,5
khair,2,100.0,100,100,3,3,6
محمود,2,100.0,100,100,3,3,6
♥️آلَشـ❣ـہآيبـ❣,2,65.0,78,52,1,2,3

In [17]:
try:
    total_members_df = total_members_df.set_index('name')
except KeyError:
    pass

In [18]:
final_name_df["Total Clan Stars"] = final_name_df['Total Stars'].sum()
combined_df = final_name_df.reindex(total_members_df.index)
combined_df.fillna(0, inplace=True)
combined_df.sort_values(["Total Attacks", 'Total Stars', 'Avg %'], ascending=False, inplace=True)

In [19]:
def colors(row):
    if row['Total Attacks'] == 2.0:
        color = "rgb(0,255,0)"
    elif row['Total Attacks'] == 1.0:
        color = "yellow"
    else:
        color = "red"
    return [f'color: {color}'] * len(row)

In [20]:
styled_df = combined_df.style.apply(colors, axis=1).format('{:.1f}')
styled_df